import './globals.css'
import { cn } from '@/lib/utils'
import { fontSans, fontSerif } from '@/lib/fonts'

export const metadata = {
  title: 'Anforcom 2023',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn(fontSans.className, fontSerif.variable, 'bg-cpurple-5')}>{children}</body>
    </html>
  )
}
