#!/bin/sh
. "C:/LOCAL D/KULIAH/ANFORCOM/anforcomweb/anforcom-web/.husky/_/husky.sh"


# Rest of your pre-commit hook script goes here
echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# Example linting command
yarn lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged
